name: Build macOS Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Check out your code
      - name: Checkout repository
        uses: actions/checkout@v4                             # checks out repo :contentReference[oaicite:7]{index=7}

      # 2. Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5                         # installs Python; caches if desired :contentReference[oaicite:8]{index=8}
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      # 3. Install dependencies and Nuitka
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Nuitka compiler
        run: pip install nuitka

      # 4A. Option A: Use the official Nuitka GitHub Action
      - name: Build with Nuitka-Action
        uses: Nuitka/Nuitka-Action@main                       # builds .app on macOS by default :contentReference[oaicite:9]{index=9}

      # 4B. Option B: Direct CLI invocation (onefile mode)
      # - name: Compile to single executable
      #   run: python -m nuitka --onefile your_script.py        # alternative manual build :contentReference[oaicite:10]{index=10}

      # 5. Upload the compiled binary
      - name: Upload macOS build artifact
        uses: actions/upload-artifact@v3                       # stores dist/* for download :contentReference[oaicite:11]{index=11}
        with:
          name: macos-executable
          path: |
            dist/*.app
            dist/*.bin
