name: Build macOS Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Python 3.11
        uses: actions/setup-python@v5   
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Nuitka compiler
        run: pip install nuitka

      - name: Compile to single executable
        run: python -m nuitka --onefile --macos-create-app-bundle --output-dir=dist --macos-app-icon=app_icon.png --enable-plugin=tk-inter ncvault_ui.py

      - name: Upload macOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-executable
          path: |
            dist/*.app
